export const themeProfiles = {
  indigo: {
    primaryColor: "bg-indigo-600",
    primaryTextColor: "text-indigo-900",
    backgroundSection: "bg-slate-50",
    accentColor: "text-indigo-600",
    accentBgColor: "bg-indigo-400/50",
    font: "font-sans",
    waveFill: "#e0e7ff",
    fromColor: "white",
    toColor: "#f8f9fc",
    shadowColor: "shadow-[0_4px_20px_rgba(79,70,229,0.1)]",
    shadowHoverColor: "shadow-[0_6px_30px_rgba(79,70,229,0.2)]",
    ctaButton: {
      base: "rounded-md w-full sm:w-auto block text-center px-6 py-3 font-semibold transition duration-300 bg-indigo-600 text-white hover:bg-indigo-500",
      outline:
        "relative text-indigo-700 after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-0 after:bg-indigo-700 after:transition-all after:duration-300 hover:after:w-full hover:text-indigo-900",
      textHover: "hover:text-indigo-300",
    },
    sectionHeading: {
      base: "tracking-tight",
      decorated: "border-l-4 pl-4",
      color: "text-indigo-900",
      size: "text-2xl sm:text-3xl md:text-4xl font-bold",
    },
    typography: {
      sectionSubtitleAbove: "text-sm font-semibold tracking-tight text-indigo-600",
      sectionSubtitle: "text-base sm:text-lg text-gray-500 leading-relaxed",
      stepTitle: "text-base font-medium text-gray-800",
      stepDescription: "text-lg sm:text-xl text-gray-700 leading-relaxed",
      body: "text-base sm:text-lg text-gray-700 leading-relaxed",
    },
  },
  green: {
    primaryColor: "bg-green-600",
    primaryTextColor: "text-green-900",
    backgroundSection: "bg-green-50",
    accentColor: "text-green-700",
    accentBgColor: "bg-green-400/50",
    font: "font-sans",
    waveFill: "#d1fae5",
    fromColor: "white",
    toColor: "#ecfdf5",
    shadowColor: "shadow-[0_4px_20px_rgba(34,197,94,0.1)]",
    shadowHoverColor: "shadow-[0_6px_30px_rgba(34,197,94,0.2)]",
    ctaButton: {
      base: "rounded-md w-full sm:w-auto block text-center px-6 py-3 font-semibold transition duration-300 bg-green-600 text-white hover:bg-green-500",
      outline:
        "relative text-green-700 after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-0 after:bg-green-700 after:transition-all after:duration-300 hover:after:w-full hover:text-green-900",
      textHover: "hover:text-green-300",
    },
    sectionHeading: {
      base: "tracking-tight",
      decorated: "border-l-4 pl-4",
      color: "text-green-900",
      size: "text-2xl sm:text-3xl md:text-4xl font-bold",
    },
    typography: {
      sectionSubtitleAbove: "text-sm font-semibold tracking-tight text-green-700",
      sectionSubtitle: "text-base sm:text-lg text-gray-500 leading-relaxed",
      stepTitle: "text-base font-medium text-gray-800",
      stepDescription: "text-lg sm:text-xl text-gray-700 leading-relaxed",
      body: "text-base sm:text-lg text-gray-700 leading-relaxed",
    },
  },
  rose: {
    primaryColor: "bg-rose-500",
    primaryTextColor: "text-rose-900",
    backgroundSection: "bg-rose-50",
    accentColor: "text-rose-600",
    accentBgColor: "bg-rose-400/50",
    font: "font-serif",
    waveFill: "#ffe4e6",
    fromColor: "white",
    toColor: "#fff1f2",
    shadowColor: "shadow-[0_4px_20px_rgba(244,63,94,0.1)]",
    shadowHoverColor: "shadow-[0_6px_30px_rgba(244,63,94,0.2)]",
    ctaButton: {
      base: "rounded-md w-full sm:w-auto block text-center px-6 py-3 font-semibold transition duration-300 bg-rose-500 text-white hover:bg-rose-400",
      outline:
        "relative text-rose-700 after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-0 after:bg-rose-700 after:transition-all after:duration-300 hover:after:w-full hover:text-rose-900",
      textHover: "hover:text-rose-300",
    },
    sectionHeading: {
      base: "tracking-tight",
      decorated: "border-l-4 pl-4",
      color: "text-rose-900",
      size: "text-2xl sm:text-3xl md:text-4xl font-bold",
    },
    typography: {
      sectionSubtitleAbove: "text-sm font-semibold tracking-tight text-rose-600",
      sectionSubtitle: "text-base sm:text-lg text-gray-500 leading-relaxed",
      stepTitle: "text-base font-medium text-gray-800",
      stepDescription: "text-lg sm:text-xl text-gray-700 leading-relaxed",
      body: "text-base sm:text-lg text-gray-700 leading-relaxed",
    },
  },
  navy: {
    primaryColor: "bg-blue-900",
    primaryTextColor: "text-blue-900",
    backgroundSection: "bg-blue-50",
    accentColor: "text-blue-700",
    accentBgColor: "bg-blue-300/50",
    font: "font-sans",
    waveFill: "#e0f2fe",
    fromColor: "white",
    toColor: "#f0f9ff",
    shadowColor: "shadow-[0_4px_20px_rgba(30,58,138,0.1)]",
    shadowHoverColor: "shadow-[0_6px_30px_rgba(30,58,138,0.2)]",
    ctaButton: {
      base: "rounded-md w-full sm:w-auto block text-center px-6 py-3 font-semibold transition duration-300 bg-blue-900 text-white hover:bg-blue-800",
      outline:
        "relative text-blue-800 after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-0 after:bg-blue-800 after:transition-all after:duration-300 hover:after:w-full hover:text-blue-900",
      textHover: "hover:text-blue-300",
    },
    sectionHeading: {
      base: "tracking-tight",
      decorated: "border-l-4 pl-4",
      color: "text-blue-900",
      size: "text-2xl sm:text-3xl md:text-4xl font-bold",
    },
    typography: {
      sectionSubtitleAbove: "text-sm font-semibold tracking-tight text-blue-700",
      sectionSubtitle: "text-base sm:text-lg text-gray-500 leading-relaxed",
      stepTitle: "text-base font-medium text-gray-800",
      stepDescription: "text-lg sm:text-xl text-gray-700 leading-relaxed",
      body: "text-base sm:text-lg text-gray-700 leading-relaxed",
    },
  },
  neutral: {
    primaryColor: "bg-zinc-700",
    primaryTextColor: "text-zinc-800",
    backgroundSection: "bg-zinc-50",
    accentColor: "text-zinc-600",
    accentBgColor: "bg-zinc-300/30",
    font: "font-sans",
    waveFill: "#f4f4f5",
    fromColor: "white",
    toColor: "#f8f8f8",
    shadowColor: "shadow-[0_4px_20px_rgba(63,63,70,0.08)]",
    shadowHoverColor: "shadow-[0_6px_30px_rgba(63,63,70,0.15)]",
    ctaButton: {
      base: "rounded-md w-full sm:w-auto block text-center px-6 py-3 font-semibold transition duration-300 bg-zinc-700 text-white hover:bg-zinc-600",
      outline:
        "relative text-zinc-700 after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-0 after:bg-zinc-700 after:transition-all after:duration-300 hover:after:w-full hover:text-zinc-800",
      textHover: "hover:text-zinc-500",
    },
    sectionHeading: {
      base: "tracking-tight",
      decorated: "border-l-4 pl-4",
      color: "text-zinc-800",
      size: "text-2xl sm:text-3xl md:text-4xl font-bold",
    },
    typography: {
      sectionSubtitleAbove: "text-sm font-semibold tracking-tight text-zinc-600",
      sectionSubtitle: "text-base sm:text-lg text-gray-500 leading-relaxed",
      stepTitle: "text-base font-medium text-gray-800",
      stepDescription: "text-lg sm:text-xl text-gray-700 leading-relaxed",
      body: "text-base sm:text-lg text-gray-700 leading-relaxed",
    },
  },
  classic: {
    primaryColor: "bg-[#bfae9e]",
    primaryTextColor: "text-[#3e3e3e]",
    backgroundSection: "bg-[#f9f6f2]",
    accentColor: "text-[#8b7c6d]",
    accentBgColor: "bg-[#dcd1c3]/40",
    font: "font-serif",
    waveFill: "#f9f6f2",
    fromColor: "white",
    toColor: "#f2ece5",
    shadowColor: "shadow-[0_4px_20px_rgba(191,174,158,0.1)]",
    shadowHoverColor: "shadow-[0_6px_30px_rgba(191,174,158,0.2)]",
    ctaButton: {
      base: "rounded-md w-full sm:w-auto block text-center px-6 py-3 font-semibold transition duration-300 bg-[#bfae9e] text-white hover:bg-[#a99887]",
      outline:
        "relative text-[#8b7c6d] after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-0 after:bg-[#8b7c6d] after:transition-all after:duration-300 hover:after:w-full hover:text-[#6d5f52]",
      textHover: "hover:text-[#bfae9e]",
    },
    sectionHeading: {
      base: "tracking-tight",
      decorated: "border-l-4 pl-4",
      color: "text-[#3e3e3e]",
      size: "text-2xl sm:text-3xl md:text-4xl font-bold",
    },
    typography: {
      sectionSubtitleAbove: "text-sm font-semibold tracking-tight text-[#8b7c6d]",
      sectionSubtitle: "text-base sm:text-lg text-gray-500 leading-relaxed",
      stepTitle: "text-base font-medium text-gray-800",
      stepDescription: "text-lg sm:text-xl text-gray-700 leading-relaxed",
      body: "text-base sm:text-lg text-gray-700 leading-relaxed",
    },
  },
} as const;

export type ThemeProfile = (typeof themeProfiles)[keyof typeof themeProfiles];
